[project]
name = "bpd_vars"
version = "1.0"
authors = [{ name = "ZetaDaemon" }]
description = """\
Allows for reading and writing BehaviorProviderDefinition variables."""
dependencies = ["command_extensions"]

[tool.sdkmod]
name = "BPD Vars"
supported_games = ["BL2", "TPS"]
license = { name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/" }

[tool.build]
skip_release = true
