name: Build

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Check out repository and submodules
              uses: actions/checkout@v7
              with:
                  submodules: recursive

            - name: Configure
              run: cmake --preset bpd-vars

            - name: Build
              run: cmake --build --preset bpd-vars-build

            - name: Package mod
              shell: pwsh
              run: |
                  Compress-Archive `
                      -Path python\bpd_vars `
                      -DestinationPath bpd_vars.zip

            - name: Upload package
              uses: actions/upload-artifact@v7
              with:
                  name: bpd-vars-package
                  path: bpd_vars.zip
